apiVersion: v1
kind: Service
metadata:
  name: mysql-primary
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql
    role: primary
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read-replica
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  selector:
    app: mysql
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: "mysql"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: mysql
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_REPLICATION_USER
          value: "replica_user"
        - name: MYSQL_REPLICATION_PASSWORD
          value: "replica_password"
        - name: MYSQL_DATABASE
          value: "app_db"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        args:
        - "--server-id=$(HOSTNAME_INDEX)"
        - "--log-bin=mysql-bin"
        - "--binlog-format=row"
        - "--default-authentication-plugin=mysql_native_password"
        - "--gtid-mode=ON"
        - "--enforce-gtid-consistency=ON"
        - "--log-slave-updates=ON"
        - "--read-only=$(if [[ \"$(HOSTNAME)\" == \"mysql-0\" ]]; then echo \"0\"; else echo \"1\"; fi)"
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi